# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dedada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=14)),
            ],
        ),
        migrations.AddField(
            model_name='dedada',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_attendance.Person'),
        ),
    ]
