# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance', '0002_auto_20160824_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workedtime',
            name='finish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workedtime_finish', to='app_attendance.Fingerprint'),
        ),
    ]
